#!/usr/bin/env bash
# Adding redirect_me block into configurations

#Check if nginx already exists

nginx_dir="/var/www/html"

if [ -d "$nginx_dir" ]; then
        echo "Nginx EXISTS"
else
	echo "Installing Nginx + 301 redirect_me block"

	#  updates the package lists for available software packages.
	sudo apt-get update -y
	# installs the Nginx web server.
	sudo apt-get install -y nginx
	# starting nginx service
	sudo service nginx start
	# allowing nginx on firewall
	sudo ufw allow 'Nginx HTTP'

	# Give the user ownership to website files for easy editing
	sudo chown -R "$USER":"$USER" /var/www/html
	sudo chmod -R 755 /var/www

	# Backup default index
	cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

	#  sets the content of the index.html file to "Hello World!" using the echo command.
	echo "Hello World!" > /var/www/html/index.nginx-debian.html

	# Sets Nginx to listen on port 80 and serve files from the default directory.
	printf %s "server {
        	listen      80;
        	listen      [::]:80 default_server;
        	root        /var/www/html;
        	index       index.nginx-debian.html index.html index.htm;
	}
	" > /etc/nginx/sites-enabled/default
fi

# Adding redirect_me block
sudo sed -i '6i\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-enabled/default

# Restarts the Nginx service to apply the configuration changes.
service nginx restart

