#!/usr/bin/env bash
# Installing Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#+    at the root with a curl GET request and add a redirect_me block.

#Check if nginx already exist and remove it

nginx_dir="/etc/nginx/html"

if [ -d "$nginx_dir" ]; then
        echo "Directory EXISTS"
        sudo rm -rf "$nginx_dir"
fi

#  updates the package lists for available software packages.
apt-get update
# installs the Nginx web server.
apt-get install -y nginx

# Creates the /etc/nginx/html directory, which will serve as the document root directory for Nginx.
mkdir /etc/nginx/html
#  creates an empty index.html file inside the /etc/nginx/html directory.
touch /etc/nginx/html/index.html
#  sets the content of the index.html file to "Hello World!" using the echo command.
echo "Hello World!" > /etc/nginx/html/index.html
# Sets Nginx to listen on port 80 and serve files from the /etc/nginx/html directory.
printf %s "server {
        listen      80;
        listen      [::]:80 default_server;
        root        /etc/nginx/html;
        index       index.html index.htm;
}
" > /etc/nginx/sites-enabled/default

# Adding redirect_me block
sudo sed -i '6i\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-enabled/default

# Restarts the Nginx service to apply the configuration changes.
service nginx restart
