#!/usr/bin/env bash
#Script that transfers a file from our client to a server

# Check if all parameters are provided
if [ $# -lt 2 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

file_path=$1
server_ip=$2
username="ubuntu"
ssh_key="~/.ssh/school"

# Transfer the file using scp
scp -o  StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip:/home/ubuntu"

exit 0
