#!/usr/bin/env bash
# Installing load balance HAproxy

balancer="
frontend haproxy_balancer
    timeout client 30000
    bind *:80
    mode http
    default_backend webservers

backend webservers
    timeout connection 3000
    timeout server 30000
    balance roundrobin
    server 319031-web-01 54.166.165.167:80 check
    server 319031-web-02 54.227.223.210:80 check
"
# Update packages
apt-get -y update

# Add HAProxy PPA
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

# Install HAProxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
